package aboutTheBank.securities;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/security") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private SecurityRepository securityRepository;

	/*
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewSecurity (@RequestParam String buyer
			, @RequestParam String seller) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Security sec = new Security();
		sec.setBuyer(buyer);
		sec.setSeller(seller);
		securityRepository.save(sec);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Security> getAllSecurities() {
		// This returns a JSON or XML with the users
		return securityRepository.findAll();
	}*/
}